name: Deploy Production
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Set up Go 1.23.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.61.0 

      - name: Run Tests
        run: go test -v ./

      - name: Build
        run: go build -v ./
  deploy-production:
    name: Deploy app to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --local-only --config fly-production.toml
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
